stages:
  preprocess:
    cmd: python src/preprocess_data.py
    deps:
    - data/raw/ben-yehuda.txt
    - data/raw/he_wiktionary-male_haser.csv
    - data/raw/he_wp-nikud.txt
    - data/raw/wikisource-haser_male.csv
    - src/preprocess_data.py
    outs:
    - data/processed/male_haser.csv
    - data/processed/nikud.csv
