stages:
  preprocessing:
    cmd: python src/preprocessing/preprocess_data.py
    deps:
    - data/raw/he_wiktionary-male_haser.csv
    - data/raw/wikisource-haser_male.csv
    outs:
    - data/processed/male_haser.csv
