stages:
  preprocess:
    cmd: python src/preprocess_data.py
    deps:
    - data/raw/ben-yehuda.txt
    - data/raw/he_wiktionary-male_haser.csv
    - data/raw/he_wp-nikud.txt
    - data/raw/wikisource-haser_male.csv
    - src/preprocess_data.py
    outs:
    - data/processed/ktiv_male.csv
    - data/processed/nikud.csv
  train-ktiv-male:
    cmd: python src/train_ktiv_male.py
    deps:
    - data/processed/ktiv_male.csv
    - src/train_ktiv_male.py
    outs:
    - models/ktiv_male
  add-ktiv-male:
    cmd: python src/add_ktiv_male.py
    deps:
    - data/processed/nikud.csv
    - models/ktiv_male
    - src/add_ktiv_male.py
    outs:
    - data/processed/nikud_with_ktiv_male.csv
