[project]
name = "unikud"
version = "0.1.0"
description = "Hebrew nikud with deep learning"
readme = "README.md"
authors = [
    { name = "Morris Alper", email = "morrisalp@gmail.com" }
]
requires-python = ">=3.10.0"
dependencies = [
    "torch == 2.6.0",
    "transformers == 4.48.3"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
